#!/bin/bash

# Set the remote repository URL
remote_repo_url="https://github.com/ruslanlap/dotfiles"

# Set the temporary directory for cloning the repository
temp_dir="$HOME/dotfiles-temp"

# Set the directory for the actual git repository
git_dir="$HOME/dotfiles"

# Clone the repository into a temporary directory
git clone --separate-git-dir="$git_dir" "$remote_repo_url" "$temp_dir"

# Sync the files from the temporary directory to the home directory
rsync --recursive --verbose --exclude '.git' "$temp_dir/" "$HOME/"

# Remove the temporary directory
rm -rf "$temp_dir"

echo alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' >> .bashrc

# Configure the git repository to not show untracked files
config config status.showUntrackedFiles no

