#!/bin/bash

# Add command to install Oh My Zsh on start
echo 'if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi' >> ${ZDOTDIR:-$HOME}/.zshrc

# Clone zsh-syntax-highlighting repository
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

# Add source line to .zshrc for zsh-syntax-highlighting
echo "source \${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc

# Clone zsh-autosuggestions repository
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Add zsh-autosuggestions to plugins in .zshrc
echo "plugins+=(zsh-autosuggestions)" >> ${ZDOTDIR:-$HOME}/.zshrc

# Clone fzf repository
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

# Install fzf
~/.fzf/install

# Clone Powerlevel10k theme repository
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Set ZSH_THEME to powerlevel10k in .zshrc
echo "ZSH_THEME=\"powerlevel10k/powerlevel10k\"" >> ${ZDOTDIR:-$HOME}/.zshrc

# Inform the user
echo "zsh-syntax-highlighting, zsh-autosuggestions, fzf, Powerlevel10k, and Oh My Zsh have been successfully installed and configured."

